# Generated by Django 4.0.4 on 2022-05-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default=' ', upload_to='meals/'),
            preserve_default=False,
        ),
    ]
