# Generated by Django 4.0.4 on 2022-05-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profile_age_alter_profile_amount_of_water_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
